from __future__ import annotations

from app.config.settings import (
    DEFAULT_CAMERA_INDEX,
    DEFAULT_DEAD_ZONE,
    DEFAULT_SENSITIVITY,
    DEFAULT_SMOOTHING,
    GESTURE_SENSITIVITY,
    GESTURE_SMOOTHING,
    HAND_LOST_TIMEOUT,
    MAX_FORWARD_PULL,
    MAX_PULL_DISTANCE,
    PINCH_RELEASE_THRESHOLD,
    PINCH_START_THRESHOLD,
)